# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': ('bank',),
                'verbose_name_plural': ('banks',),
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('banks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.Bank')),
            ],
            options={
                'verbose_name': ('company',),
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyfarms', to='companies.Company')),
            ],
            options={
                'verbose_name': ('companyfarm',),
                'verbose_name_plural': ('companyfarms',),
                'db_table': 'companyfarm',
            },
        ),
        migrations.CreateModel(
            name='CurrentAccountingFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': ('currentaccountingfirm',),
                'verbose_name_plural': ('currentaccountingfirms',),
                'db_table': 'currentaccountingfirm',
            },
        ),
        migrations.CreateModel(
            name='FarmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'farmtype',
                'verbose_name_plural': 'farmtypes',
                'db_table': 'farmtype',
            },
        ),
        migrations.AddField(
            model_name='companyfarm',
            name='farm_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_farm', to='companies.FarmType'),
        ),
        migrations.AddField(
            model_name='company',
            name='current_accounting_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.CurrentAccountingFirm'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
